runtime: nodejs20
instance_class: F1

env_variables:
  INSTANCE_CONNECTION_NAME: ${api-baru-457709:asia-southeast2:instance1}
  DB_USER: ${AMOGA}
  DB_PASSWORD: ${AMOGA}
  DB_NAME: ${market}
  JWT_SECRET: ${AMOGA}

beta_settings:
  cloud_sql_instances: ${api-baru-457709:asia-southeast2:instance1}

automatic_scaling:
  min_instances: 0
  max_instances: 3
