runtime: nodejs20
instance_class: F1

env_variables:
  INSTANCE_CONNECTION_NAME: ${INSTANCE_CONNECTION_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME}
  JWT_SECRET: ${JWT_SECRET}

beta_settings:
  cloud_sql_instances: ${INSTANCE_CONNECTION_NAME}

automatic_scaling:
  min_instances: 0
  max_instances: 3
